SleepMode: Fix crash on enabling
  java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.android.internal.util.derp.SleepModeController.addNotification(SleepModeController.java:445)
        at com.android.internal.util.derp.SleepModeController.enable(SleepModeController.java:344)
        at com.android.internal.util.derp.SleepModeController.setSleepMode(SleepModeController.java:485)
        at com.android.internal.util.derp.SleepModeController.access$300(SleepModeController.java:50)
        at com.android.internal.util.derp.SleepModeController$SettingsObserver.update(SleepModeController.java:511)
        at com.android.internal.util.derp.SleepModeController$SettingsObserver.onChange(SleepModeController.java:505)
        at android.database.ContentObserver.onChange(ContentObserver.java:169)
        at android.database.ContentObserver.onChange(ContentObserver.java:187)
        at android.database.ContentObserver.onChange(ContentObserver.java:200)
        at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
        at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.android.server.SystemServer.run(SystemServer.java:920)
        at com.android.server.SystemServer.main(SystemServer.java:623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
7aac57