SystemUI: Add missing gesture assets
E/BackGestureTfClassifier: Load vocab file error:
    java.io.FileNotFoundException: backgesture.vocab
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:881)
        at android.content.res.AssetManager.open(AssetManager.java:858)
        at com.google.android.systemui.gesture.BackGestureTfClassifierProviderGoogle.loadVocab(Unknown Source:11)
        at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler.updateMLModelState(EdgeBackGestureHandler.java:681)
        at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler.updateIsEnabled(EdgeBackGestureHandler.java:593)
        at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler.onNavBarAttached(EdgeBackGestureHandler.java:476)
        at com.android.systemui.navigationbar.NavigationBarView.onAttachedToWindow(NavigationBarView.java:1341)
        at android.view.View.dispatchAttachedToWindow(View.java:20812)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
...